import type { Metadata } from "next";
import { inter } from "@/public/fonts";
import "@/src/styles/globals.css";
import Header from "../components/layout/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body
        className={`${inter.className} min-h-[calc(100vh-20px)] flex flex-col`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
